-- Enable required extensions
create extension if not exists "pgcrypto";
create extension if not exists "vector";

------------------------------------------------------------
-- DOCUMENTS TABLE
------------------------------------------------------------
CREATE TABLE public.documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  file_name text NOT NULL,
  summary text,
  body text NOT NULL,
  source_path text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  topic text[],                 
  content_hash text UNIQUE,
  embedding_avg vector(1536),  
  pdf_url text,
  CONSTRAINT documents_pkey PRIMARY KEY (id)
);

------------------------------------------------------------
-- TOPICS TABLE
------------------------------------------------------------
CREATE TABLE public.topics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  description text,
  key_words text[],             
  CONSTRAINT topics_pkey PRIMARY KEY (id)
);

------------------------------------------------------------
-- TOPICS_TEST TABLE
------------------------------------------------------------
CREATE TABLE public.topics_test (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  name text NOT NULL,
  key_words text[] DEFAULT '{}'::text[],
  model_topic_index integer,
  name_manual text,
  key_words_manual text[],
  is_active boolean DEFAULT true,
  descripcion text,
  descripcion_manual text,
  CONSTRAINT topics_test_pkey PRIMARY KEY (id)
);

------------------------------------------------------------
-- CHUNKS TABLE
------------------------------------------------------------
CREATE TABLE public.chunks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  document_id uuid NOT NULL,
  chunk_idx integer NOT NULL,
  hpath text,
  body text NOT NULL,
  created_at timestamptz DEFAULT now(),
  topic_id uuid,
  page_number integer,
  feedback_score integer DEFAULT 0,
  CONSTRAINT chunks_pkey PRIMARY KEY (id),
  CONSTRAINT chunks_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents(id),
  CONSTRAINT chunks_topic_id_fkey FOREIGN KEY (topic_id) REFERENCES public.topics(id)
);

------------------------------------------------------------
-- CHUNK EMBEDDINGS TABLE
------------------------------------------------------------
CREATE TABLE public.chunk_embeddings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  chunk_id uuid NOT NULL,
  embedding vector(1536),       
  created_at timestamptz DEFAULT now(),
  CONSTRAINT chunk_embeddings_pkey PRIMARY KEY (id),
  CONSTRAINT chunk_embeddings_chunk_id_fkey FOREIGN KEY (chunk_id) REFERENCES public.chunks(id)
);

------------------------------------------------------------
-- FEEDBACK TABLE
------------------------------------------------------------
CREATE TABLE public.feedback (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  user_id varchar,
  session_id varchar,
  query text NOT NULL,
  answer text NOT NULL,
  rating integer CHECK (rating IN (-1, 1)),
  feedback_type varchar,
  comment text,
  citations jsonb,
  retrieved_passages jsonb,
  model_used varchar,
  created_at timestamp DEFAULT now(),
  query_embedding vector(1536),   
  is_verified boolean NOT NULL DEFAULT false,
  CONSTRAINT feedback_pkey PRIMARY KEY (id)
);

------------------------------------------------------------
-- USER PROFILES TABLE
------------------------------------------------------------
CREATE TABLE public.user_profiles (
  user_id uuid NOT NULL,
  role text,
  level integer,
  preferences jsonb DEFAULT '{}'::jsonb,
  completed_material_ids text[],
  time_budget_default integer,
  CONSTRAINT user_profiles_pkey PRIMARY KEY (user_id)
);
